# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NodeJS MQI Prebuild

# Only run this workflow when manually triggered
on:
  workflow_dispatch:

# Don't try to install the MQ Client package
env:
  MQIJS_NOREDIST: true

jobs:
  build:

    strategy:
      matrix:
        # node-version: [14.x, 16.x, 18.x]
        node-version: [18.x]
        # MacOS public runners do not yet support M1 hardware
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: | 
        npm install -g prebuildify
        npm ci
        npm run prebuild --if-present
        npm test
    - name: Store prebuilt libraries
      uses: actions/upload-artifact@v3
      with:
        name: prebuilds
        retention-days: 1
        path: |
          prebuilds/
